// Code generated by "stringer -type PinOptState"; DO NOT EDIT.

package hilib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PinAvailable-258]
}

const _PinOptState_name = "PinAvailable"

var _PinOptState_index = [...]uint8{0, 12}

func (i PinOptState) String() string {
	i -= 258
	if i < 0 || i >= PinOptState(len(_PinOptState_index)-1) {
		return "PinOptState(" + strconv.FormatInt(int64(i+258), 10) + ")"
	}
	return _PinOptState_name[_PinOptState_index[i]:_PinOptState_index[i+1]]
}
