// Code generated by "stringer -type SimState"; DO NOT EDIT.

package hilib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SimPinLocked-260]
}

const _SimState_name = "SimPinLocked"

var _SimState_index = [...]uint8{0, 12}

func (i SimState) String() string {
	i -= 260
	if i < 0 || i >= SimState(len(_SimState_index)-1) {
		return "SimState(" + strconv.FormatInt(int64(i+260), 10) + ")"
	}
	return _SimState_name[_SimState_index[i]:_SimState_index[i+1]]
}
