// Code generated by "stringer -type SimStatus"; DO NOT EDIT.

package hilib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SimMissing-255]
}

const _SimStatus_name = "SimMissing"

var _SimStatus_index = [...]uint8{0, 10}

func (i SimStatus) String() string {
	i -= 255
	if i < 0 || i >= SimStatus(len(_SimStatus_index)-1) {
		return "SimStatus(" + strconv.FormatInt(int64(i+255), 10) + ")"
	}
	return _SimStatus_name[_SimStatus_index[i]:_SimStatus_index[i+1]]
}
