// Code generated by "stringer -type SMSType"; DO NOT EDIT.

package hilib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NormalSMS-0]
}

const _SMSType_name = "NormalSMS"

var _SMSType_index = [...]uint8{0, 9}

func (i SMSType) String() string {
	if i < 0 || i >= SMSType(len(_SMSType_index)-1) {
		return "SMSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SMSType_name[_SMSType_index[i]:_SMSType_index[i+1]]
}
